export const layoutTransitionPropertyList = [
  "all",
  "max-width",
  "max-height",
  "width",
  "height",
  "min-width",
  "min-height",
  "top",
  "bottom",
  "left",
  "right",
  "inset",
  "inset-block",
  "inset-inline",
  "inset-block-start",
  "inset-block-end",
  "inset-inline-start",
  "inset-inline-end",
  "margin",
  "margin-inline",
  "margin-block",
  "margin-top",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "padding",
  "padding-inline",
  "padding-block",
  "padding-top",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "border-width",
  "border-top-width",
  "border-bottom-width",
  "border-left-width",
  "border-right-width",
  "font-size",
  "line-height",
  "letter-spacing",
  "word-spacing",
  "flex-basis",
  "grid-template-columns",
  "grid-template-rows",
] as const

export const layoutAnimationMutationPropertyList = [
  "width",
  "height",
  "min-width",
  "max-width",
  "min-height",
  "max-height",
  "top",
  "bottom",
  "inset",
  "inset-block",
  "inset-block-start",
  "inset-block-end",
  "inset-inline",
  "inset-inline-start",
  "inset-inline-end",
  "margin",
  "margin-top",
  "margin-bottom",
  "margin-inline",
  "margin-block",
  "padding",
  "padding-top",
  "padding-bottom",
  "padding-inline",
  "padding-block",
  "border-width",
  "border-top-width",
  "border-bottom-width",
  "border-left-width",
  "border-right-width",
  "font-size",
  "line-height",
  "letter-spacing",
  "word-spacing",
  "flex-basis",
  "grid-template-columns",
  "grid-template-rows",
] as const

export const layoutStatefulShiftPropertyList = [
  "width",
  "height",
  "min-width",
  "min-height",
  "padding",
  "padding-top",
  "padding-bottom",
  "padding-left",
  "padding-right",
  "margin",
  "margin-top",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "border-width",
  "border-top-width",
  "border-bottom-width",
  "border-left-width",
  "border-right-width",
  "font-size",
  "line-height",
  "top",
  "bottom",
  "inset",
  "inset-block",
  "inset-block-start",
  "inset-block-end",
  "transform",
  "translate",
] as const

export const layoutClassGeometryPropertyList = [
  "display",
  "position",
  "top",
  "bottom",
  "margin-top",
  "margin-bottom",
  "padding-top",
  "padding-bottom",
  "height",
  "min-height",
  "width",
  "min-width",
  "font-size",
  "line-height",
  "transform",
  "translate",
  "box-sizing",
] as const

export const layoutInlineStyleTogglePropertyList = [
  "display",
  "position",
  "top",
  "bottom",
  "margin-top",
  "margin-bottom",
  "padding-top",
  "padding-bottom",
  "height",
  "min-height",
  "width",
  "min-width",
  "line-height",
  "font-size",
] as const

export const layoutPositionedOffsetPropertyList = [
  "top",
  "bottom",
  "inset",
  "inset-block",
  "inset-block-start",
  "inset-block-end",
] as const

export const layoutPositionedOffsetSignalList = [
  "top",
  "bottom",
  "inset-block-start",
  "inset-block-end",
] as const

export const LAYOUT_TRANSITION_PROPERTIES = new Set<string>(layoutTransitionPropertyList)
export const LAYOUT_ANIMATION_MUTATION_PROPERTIES = new Set<string>(layoutAnimationMutationPropertyList)
export const LAYOUT_STATEFUL_SHIFT_PROPERTIES = new Set<string>(layoutStatefulShiftPropertyList)
export const LAYOUT_CLASS_GEOMETRY_PROPERTIES = new Set<string>(layoutClassGeometryPropertyList)
export const LAYOUT_INLINE_STYLE_TOGGLE_PROPERTIES = new Set<string>(layoutInlineStyleTogglePropertyList)
export const LAYOUT_POSITIONED_OFFSET_PROPERTIES = new Set<string>(layoutPositionedOffsetPropertyList)
export const LAYOUT_POSITIONED_OFFSET_SIGNALS = new Set<string>(layoutPositionedOffsetSignalList)
