/**
 * Shared Utilities
 *
 * General-purpose string, CSS, HTML, and parsing utilities
 * used across ganko, ganko, and ganko-vscode.
 */

export {
  CHAR_SPACE,
  CHAR_TAB,
  CHAR_NEWLINE,
  CHAR_CR,
  CHAR_FORM_FEED,
  CHAR_HASH,
  CHAR_DOT,
  CHAR_COLON,
  CHAR_AMPERSAND,
  CHAR_ASTERISK,
  CHAR_PERCENT,
  CHAR_OPEN_PAREN,
  CHAR_CLOSE_PAREN,
  CHAR_OPEN_BRACKET,
  CHAR_CLOSE_BRACKET,
  CHAR_OPEN_BRACE,
  CHAR_CLOSE_BRACE,
  CHAR_GT,
  CHAR_PLUS,
  CHAR_TILDE,
  CHAR_COMMA,
  CHAR_HYPHEN,
  CHAR_UNDERSCORE,
  CHAR_SEMICOLON,
  CHAR_EXCLAIM,
  CHAR_DOLLAR,
  CHAR_AT,
  CHAR_BACKSLASH,
  CHAR_SLASH,
  CHAR_DOUBLE_QUOTE,
  CHAR_SINGLE_QUOTE,
  CHAR_A,
  CHAR_E,
  CHAR_H,
  CHAR_I,
  CHAR_M,
  CHAR_N,
  CHAR_O,
  CHAR_P,
  CHAR_R,
  CHAR_S,
  CHAR_T,
  CHAR_U,
  CHAR_V_LOWER,
  CHAR_V_UPPER,
  CHAR_0,
  CHAR_9,
  CHAR_A_UPPER,
  CHAR_F_UPPER,
  CHAR_Z_UPPER,
  CHAR_A_LOWER,
  CHAR_F_LOWER,
  CHAR_Z_LOWER,
  CHAR_PIPE,
  CHAR_QUESTION,
  WHITESPACE_TABLE,
  SEMICOLON_OR_WHITESPACE_TABLE,
  isDigit,
  isUpperAlpha,
  isLowerAlpha,
  isAlpha,
  isAlphaNumeric,
  isHexDigit,
  isWhitespace,
  isCombinator,
  isIdentStart,
  isIdentChar,
  isPseudoNameChar,
  isHexColor,
  isRootSelector,
  toLowerCode,
  isWhitespaceOrCombinator,
  matchesLowercase,
} from "./chars";

export {
  EMPTY_STRINGS,
  splitByComma,
  splitByCommaRobust,
  splitParameters,
  splitSelectorList,
  splitPseudoArgs,
  splitMediaQueries,
  trimFast,
  getTrimBounds,
  toLowerString,
  isBlank,
  indexOfAtDepthZero,
  findMatchingParen,
  skipQuotedString,
  findClosingParenRobust,
  findClosingBracketRobust,
  extractParenContent,
  stripVarPrefix,
  endsWithCaseInsensitive,
  startsWithCaseInsensitive,
  isKebabCase,
  toKebabCase,
  isCSSFile,
  isSCSSFile,
  isTypeScriptFile,
  isTSXFile,
  isJSXFile,
  isJSFile,
  countLines,
  type SplitOptions,
} from "./string";

export { StringInterner } from "./string-intern";

export { HTML_VOID_ELEMENTS, HEADING_ELEMENTS, isVoidElement, isDomElement } from "./html";

export {
  HOOK_PATTERN,
  COMPONENT_PATTERN,
  EVENT_HANDLER_PATTERN,
  EVENT_HANDLER_VAR_PATTERN,
  ID_STICKY,
  CLASS_STICKY,
  ATTRIBUTE_STICKY,
  PSEUDO_ELEMENT_STICKY,
  PSEUDO_CLASS_STICKY,
  ELEMENT_STICKY,
  HAS_ID_RE,
  HAS_UNIVERSAL_RE,
  HAS_ATTRIBUTE_RE,
  ID_GLOBAL,
  CLASS_GLOBAL,
  ATTRIBUTE_GLOBAL,
  PSEUDO_ELEMENT_GLOBAL,
  PSEUDO_CLASS_GLOBAL,
  FUNCTIONAL_PSEUDO_GLOBAL,
  UNIVERSAL_SELECTOR_RE,
  COMBINATOR_SPLIT_RE,
  WHITESPACE_SPLIT,
  WHITESPACE_ONLY_RE,
  WHERE_CONTENT_RE,
  SPECIFICITY_PSEUDO_RE,
  FUNCTION_CALL_RE,
  CONTAINER_RE,
  MEDIA_TYPE_RE,
  MEDIA_FEATURE_RE,
  MEDIA_RANGE_RE,
  MEDIA_COLON_RE,
  IMPORTANT_SUFFIX_RE,
  TIME_VALUE_RE,
  NUMBER_RE,
  DURATION_RE,
  INTEGER_RE,
  TIMING_FUNCTION_RE,
  matchesGlobPattern,
  matchesAnyGlobPattern,
} from "./patterns";

export {
  isAnimationKeyword,
  isTimeValue,
  isIterationCount,
  isTimingFunction,
  isAnimationValue,
  extractKeyframeNames,
} from "./animation";

export {
  parseInlineStyle,
  default as parseInlineStyleDefault,
  type Position,
  type Declaration,
  type Comment,
  type StyleNode,
  type ParseOptions,
  type ParseError,
} from "./inline-style-parser";

export { default as isHtml } from "./is-html";

export { knownCSSProperties, type KnownCSSProperties } from "./known-css-properties";

export {
  styleToObject,
  default as styleToObjectDefault,
  type StyleObject,
} from "./style-to-object";

export { computeContentHash, simpleHash } from "./hash";
